# Generated by Django 4.0.4 on 2022-06-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KonturMarketDBGood',
            fields=[
                ('egais_code', models.CharField(help_text='Код алкогольной продукции (код АП) в ЕГАИС', max_length=19, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Полное ЕГАИС наименование товара', max_length=200)),
                ('capacity', models.DecimalField(decimal_places=3, help_text='Емкость тары', max_digits=5)),
                ('is_draft', models.BooleanField(default=False, help_text='Признак разливного пива')),
            ],
        ),
        migrations.CreateModel(
            name='KonturMarketDBProducer',
            fields=[
                ('fsrar', models.CharField(help_text='Уникальный ЕГАИС идентификатор производителя', max_length=12, primary_key=True, serialize=False)),
                ('inn', models.CharField(help_text='ИНН производителя', max_length=12, null=True)),
                ('short_name', models.CharField(help_text='Короткое наименование производителя', max_length=200)),
                ('full_name', models.CharField(help_text='Полное наименование производителя', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MoySkladDBGood',
            fields=[
                ('uuid', models.CharField(help_text='Уникальный идентификатор товара', max_length=36, primary_key=True, serialize=False, unique=True)),
                ('parent_uuid', models.CharField(help_text='Уникальный идентификатор родительского товара. Для модификация товаров', max_length=36)),
                ('full_name', models.CharField(help_text='Полное имя товара', max_length=200, unique=True)),
                ('path_name', models.CharField(help_text='Папка товара', max_length=100)),
                ('style', models.CharField(help_text='Стиль пива, если товар - пиво', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара', max_digits=5)),
                ('brewery', models.CharField(help_text='Наименование пивоварни', max_length=100)),
                ('name', models.CharField(help_text='Наименование товара', max_length=100)),
                ('abv', models.FloatField(help_text='Содержание алкоголя')),
                ('og', models.FloatField(help_text='Начальная плотность')),
                ('ibu', models.PositiveSmallIntegerField(help_text='Горечь')),
                ('is_alco', models.BooleanField(default=False, help_text='Признак алкогольного напитка')),
                ('is_draft', models.BooleanField(default=False, help_text='Признак разливного пива')),
                ('bev_type', models.CharField(choices=[('beer', 'beer'), ('cider', 'cider'), ('kombucha', 'kombucha'), ('lemonade', 'lemonade'), ('mead', 'mead'), ('other', 'other')], help_text='Тип продукта', max_length=8)),
                ('capacity', models.DecimalField(decimal_places=3, help_text='Емкость тары', max_digits=5)),
                ('egais_code', models.ManyToManyField(help_text='Код алкогольной продукции', to='Sync_app.konturmarketdbgood')),
            ],
        ),
        migrations.CreateModel(
            name='KonturMarketDBStock',
            fields=[
                ('quantity', models.PositiveSmallIntegerField(help_text='Остаток товара на остатках в ЕГАИС на 2ом регистре', null=True)),
                ('egais_code', models.OneToOneField(help_text='Код алкогольной продукции (код АП) в ЕГАИС', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sync_app.konturmarketdbgood')),
            ],
        ),
        migrations.CreateModel(
            name='MoySkladDBStock',
            fields=[
                ('quantity', models.PositiveSmallIntegerField(help_text='Остаток товара на складе')),
                ('uuid', models.OneToOneField(help_text='Уникальный идентификатор товара', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sync_app.moyskladdbgood')),
            ],
        ),
        migrations.AddField(
            model_name='konturmarketdbgood',
            name='fsrar',
            field=models.ForeignKey(help_text='Уникальный ЕГАИС идентификатор производителя', on_delete=django.db.models.deletion.CASCADE, to='Sync_app.konturmarketdbproducer'),
        ),
        migrations.AddIndex(
            model_name='moyskladdbgood',
            index=models.Index(fields=['full_name'], name='Sync_app_mo_full_na_9395d0_idx'),
        ),
        migrations.AddIndex(
            model_name='moyskladdbgood',
            index=models.Index(fields=['brewery'], name='Sync_app_mo_brewery_a000fd_idx'),
        ),
        migrations.AddIndex(
            model_name='moyskladdbgood',
            index=models.Index(fields=['name'], name='Sync_app_mo_name_c19f4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='moyskladdbgood',
            constraint=models.CheckConstraint(check=models.Q(('bev_type__in', ['beer', 'cider', 'kombucha', 'lemonade', 'mead', 'other'])), name='valid_good_type'),
        ),
        migrations.AddIndex(
            model_name='konturmarketdbgood',
            index=models.Index(fields=['full_name'], name='Sync_app_ko_full_na_48e596_idx'),
        ),
    ]
