# Generated by Django 4.0.5 on 2022-06-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0002_moyskladdbretaildemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladdbretaildemand',
            name='demand_date',
            field=models.DateField(blank=True, default=None, help_text='Дата продажи', null=True),
        ),
    ]
