# Generated by Django 4.0.5 on 2022-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0003_alter_moyskladdbretaildemand_demand_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='konturmarketdbgood',
            name='kind_code',
            field=models.IntegerField(default=None, help_text='Код вида продукции'),
        ),
    ]
