# Generated by Django 4.0.5 on 2022-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0004_konturmarketdbgood_kind_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='egais_code',
            field=models.ManyToManyField(help_text='Код алкогольной продукции', related_name='goods', to='Sync_app.konturmarketdbgood'),
        ),
    ]
