# Generated by Django 4.0.5 on 2022-07-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0005_alter_moyskladdbgood_egais_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konturmarketdbstock',
            name='egais_code',
            field=models.OneToOneField(db_column='egais_code', help_text='Код алкогольной продукции (код АП) в ЕГАИС', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sync_app.konturmarketdbgood'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='egais_code',
            field=models.ManyToManyField(help_text='Код алкогольной продукции', to='Sync_app.konturmarketdbgood'),
        ),
        migrations.AlterField(
            model_name='moyskladdbstock',
            name='uuid',
            field=models.OneToOneField(db_column='uuid', help_text='Уникальный идентификатор товара', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sync_app.moyskladdbgood'),
        ),
    ]
