# Generated by Django 4.0.6 on 2022-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0006_alter_konturmarketdbstock_egais_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konturmarketdbgood',
            options={'verbose_name': 'Товар (Контур.Маркет)', 'verbose_name_plural': 'Товары (Контур.Маркет)'},
        ),
        migrations.AlterModelOptions(
            name='moyskladdbgood',
            options={'verbose_name': 'МойСклад. Наименование товара', 'verbose_name_plural': 'МойСклад. Наименование товаров'},
        ),
        migrations.RemoveConstraint(
            model_name='moyskladdbgood',
            name='valid_good_type',
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='abv',
            field=models.FloatField(help_text='Содержание алкоголя', verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='bev_type',
            field=models.CharField(choices=[('beer', 'Пиво'), ('cider', 'Сидр'), ('kombucha', 'Комбуча'), ('lemonade', 'Лимонад'), ('mead', 'Медовуха'), ('other', 'Другое')], help_text='Тип продукта', max_length=8, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='brewery',
            field=models.CharField(help_text='Наименование пивоварни', max_length=100, verbose_name='Пивоварня'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='capacity',
            field=models.DecimalField(decimal_places=3, help_text='Емкость тары', max_digits=5, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='egais_code',
            field=models.ManyToManyField(help_text='Код алкогольной продукции', related_name='goods', to='Sync_app.konturmarketdbgood', verbose_name='ЕГАИС код'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='full_name',
            field=models.CharField(help_text='Полное имя товара', max_length=200, unique=True, verbose_name='ПОлное наименование'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='ibu',
            field=models.PositiveSmallIntegerField(help_text='Горечь', verbose_name='Горечь'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='is_alco',
            field=models.BooleanField(default=False, help_text='Признак алкогольного напитка', verbose_name='Алкогольная продукция'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Признак разливного пива', verbose_name='Розлив'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='name',
            field=models.CharField(help_text='Наименование товара', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='og',
            field=models.FloatField(help_text='Начальная плотность', verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена товара', max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='style',
            field=models.CharField(help_text='Стиль пива, если товар - пиво', max_length=100, verbose_name='Стиль'),
        ),
        migrations.AddConstraint(
            model_name='moyskladdbgood',
            constraint=models.CheckConstraint(check=models.Q(('bev_type__in', ['beerПиво', 'ciderСидр', 'kombuchaКомбуча', 'lemonadeЛимонад', 'meadМедовуха', 'otherДругое'])), name='valid_good_type'),
        ),
    ]
