# Generated by Django 4.0.6 on 2022-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0007_alter_konturmarketdbgood_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moyskladdbgood',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='full_name',
            field=models.CharField(help_text='Полное имя товара', max_length=200, unique=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='parent_uuid',
            field=models.CharField(help_text='Уникальный идентификатор родительского товара. Для модификация товаров', max_length=36, verbose_name='Родительский товар (для модификаций)'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='path_name',
            field=models.CharField(help_text='Папка товара', max_length=100, verbose_name='Каталог товара'),
        ),
        migrations.AlterField(
            model_name='moyskladdbgood',
            name='uuid',
            field=models.CharField(help_text='Уникальный идентификатор товара', max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор товара'),
        ),
    ]
