# Generated by Django 4.0.6 on 2022-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sync_app', '0008_alter_moyskladdbgood_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moyskladdbgood',
            name='valid_good_type',
        ),
        migrations.AddConstraint(
            model_name='moyskladdbgood',
            constraint=models.CheckConstraint(check=models.Q(('bev_type__in', ['beer', 'cider', 'kombucha', 'lemonade', 'mead', 'other'])), name='valid_good_type'),
        ),
    ]
